-- =====================================================================
--  CONTENIDO DEL FORMULARIO
-- =====================================================================
DOC = {}
local function CAP(num, title, blocks) DOC[#DOC + 1] = {num = num, title = title, blocks = blocks} end
local function h(t) return {"h", t} end
local function p(t) return {"p", t} end
local function b(t) return {"b", t} end
local function f(t, n) return {"f", t, n} end
local function n(t) return {"n", t} end
local function tab(hd, rows) return {"t", hd, rows} end

-- ------------------------------------------------------------ 01
CAP("C01", "Suelos, Darcy y K", {
  h("Porosidad"),
  f([[n = \frac{V_{vac}}{V_{T}} \qquad n_{e} = \frac{V_{drenado}}{V_{T}}]], "n_e: fracción que participa en el flujo"),
  tab({"Suelo", "n [%]", "ne [%]"}, {{"Arcillas", "50", "4"}, {"Limos", "48", "8"}, {"Arenas", "40", "33"}, {"Gravas", "25", "22"}, {"Rocas", "1-8", "0.5-4"}}),
  h("Formaciones"),
  tab({"Tipo", "Almacena", "Transmite", "Ejemplo"}, {{"Acuífero", "alta", "alta", "gravas, arenas"}, {"Acuitardo", "alta", "baja", "limos"},
    {"Acuicludo", "alta", "nula", "arcillas"}, {"Acuífugo", "nula", "nula", "rocas"}}),
  h("Carga hidráulica"),
  f([[h = z + \frac{p}{\gamma} + \frac{v^{2}}{2g} \approx z + \frac{p}{\gamma}]], "v muy pequeña en flujo subterráneo"),
  h("Ley de Darcy (Re < 4)"),
  f([[Q = -K A \frac{dh}{dl} = K A i]]),
  f([[v = \frac{Q}{A} = K i \qquad v_{r} = \frac{v}{n_{e}}]], "v: velocidad de Darcy; vr: velocidad real"),
  f([[v = -K \nabla h \qquad K_{x} = K_{y} = K_{z} \Rightarrow \text{isotrópico}]]),
  f([[K = k \frac{\rho g}{\mu} \qquad 1 \text{darcy} = 9.87 \times 10^{-9} cm^{2}]]),
  h("Métodos indirectos"),
  f([[K = C d_{10}^{2} \qquad [cm/s], d_{10} [cm] ]], "Hazen: arenas con d10 = 0.1–0.3 mm"),
  tab({"Arena", "C"}, {{"muy fina / con finos", "40-80"}, {"media bien distribuida", "80-120"}, {"gruesa mal distribuida", "80-120"}, {"gruesa limpia", "120-150"}}),
  f([[K = \frac{\gamma}{\mu} \frac{10.0219 d_{10}^{2}}{K_{1}}]], "Slichter (1/K1 de tabla según n)"),
  tab({"n", "1/K1", "n", "1/K1"}, {{"0.26", "0.00187", "0.38", "0.04154"}, {"0.28", "0.01517", "0.40", "0.04922"}, {"0.30", "0.01905", "0.42", "0.05789"},
    {"0.32", "0.02356", "0.44", "0.06776"}, {"0.34", "0.02878", "0.46", "0.07838"}, {"0.36", "0.03473", "", ""}}),
  f([[K = \frac{\rho g}{\mu} \frac{n^{3}}{(1-n)^{2}} \frac{d_{50}^{2}}{180}]], "Kozeny–Carman"),
  h("Métodos directos"),
  f([[K = \frac{4 L Q}{\pi (h_{1} - h_{2}) D^{2}}]], "Permeámetro de carga constante (h1−h2 < 0.5 L)"),
  f([[K = \frac{d_{t}^{2} L}{d_{c}^{2} t} \ln \p{\frac{h_{0}}{h}}]], "Permeámetro de carga variable (cohesivos)"),
  f([[f = \frac{R}{2(t_{2} - t_{1})} \ln \p{\frac{2h_{1} + R}{2h_{2} + R}}]], "Método Porchet"),
  f([[K \approx \frac{L^{2}}{\bar{t} \Delta h}]], "Dos pozos de observación"),
  f([[\ln \p{\frac{C_{0}}{C}} = \frac{4 v}{\pi D} t , \quad v = K i]], "Trazador en un pozo"),
  h("Estratificación"),
  f([[K_{eq} = \frac{\Sigma K_{i} m_{i}}{\Sigma m_{i}}]], "Flujo paralelo a los estratos"),
  f([[K_{eq} = \frac{\Sigma m_{i}}{\Sigma \frac{m_{i}}{K_{i}}}]], "Flujo perpendicular a los estratos"),
  h("Propiedades del acuífero"),
  f([[T = K m \qquad V_{dren} = S A \Delta h]]),
})

-- ------------------------------------------------------------ 02
CAP("C02", "Pozos en régimen permanente", {
  h("Almacenamiento"),
  f([[S_{s} = g \rho (\alpha + \eta \beta) \qquad S = S_{s} m]], "Confinado: 1E−4 < S < 0.005"),
  f([[S = S_{y} = n_{e}]], "Libre: 0.05 < S < 0.2"),
  h("Ecuación general (confinado)"),
  f([[\frac{\partial}{\partial x}\p{K_{x}\frac{\partial h}{\partial x}} + \frac{\partial}{\partial y}\p{K_{y}\frac{\partial h}{\partial y}} + \frac{\partial}{\partial z}\p{K_{z}\frac{\partial h}{\partial z}} = S_{s}\frac{\partial h}{\partial t}]]),
  f([[\nabla^{2} h = 0]], "Permanente, homogéneo, isotrópico (Laplace)"),
  f([[\frac{1}{r}\frac{\partial h}{\partial r} + \frac{\partial^{2} h}{\partial r^{2}} + \frac{1}{r^{2}}\frac{\partial^{2} h}{\partial \theta^{2}} + \frac{\partial^{2} h}{\partial z^{2}} = 0]], "Laplace en cilíndricas"),
  h("Supuestos"),
  b("Acuífero homogéneo, isótropo, infinito; nivel inicial horizontal."),
  b("Flujo radial; radio de influencia R; sin pérdidas en el pozo."),
  h("Pozo de penetración total"),
  f([[\Delta h = H - h = \frac{Q}{2 \pi T} \ln \p{\frac{R}{r}}]], "Thiem – acuífero confinado"),
  f([[H^{2} - h^{2} = \frac{Q}{\pi K} \ln \p{\frac{R}{r}}]], "Dupuit – acuífero libre (Dupuit–Forchheimer)"),
  f([[\Delta h = \frac{Q}{2 \pi K H} \ln \frac{R}{r}]], "Libre con Δh < 0.1 H"),
  f([[\Delta h' = \Delta h - \frac{\Delta h^{2}}{2H} = \frac{Q}{2 \pi K H} \ln \frac{R}{r}]], "Corrección de Jacob (Δh < 0.5 H)"),
  h("Acuífero libre de gran potencia"),
  f([[\Delta h = \frac{Q}{4 \pi K} \p{\frac{1}{r} - \frac{1}{R}}]], "Escurrimiento esférico"),
  f([[\Delta h = \frac{Q}{2 \pi K} \p{\frac{1}{r} - \frac{1}{R}}]], "Pozo somero: semi-esférico"),
  h("Penetración parcial (confinado)"),
  f([[h_{1} - h_{2} = \frac{Q}{2 \pi K} \p{\frac{1}{b} \ln \frac{1.6 b}{r_{2}} - \frac{1}{b}\text{asinh}\frac{b}{r_{1}}}]], "Girinsky (b/m < 0.3)"),
  f([[h_{1} - h_{2} = \frac{Q}{2 \pi K m}\b{\ln\frac{r_{1}}{r_{2}} + \text{asinh}\frac{m}{r_{1}} - \text{asinh}\frac{m}{r_{2}} - \frac{m}{b}\p{\text{asinh}\frac{b}{r_{1}} - \text{asinh}\frac{b}{r_{2}}}}]], "Nasberg (b/m ≥ 0.3)"),
  h("Radio de influencia"),
  f([[R = 3000 \Delta h_{0} \sqrt{K}]], "Sichardt: R [m], Δh0 [m], K [m/s]"),
  tab({"Material", "D [mm]", "R [m]"}, {{"Gravas", ">10", "1500"}, {"Gravillas", "2-10", "500-1500"}, {"Gravilla-arcilla", "1-2", "400-500"},
    {"Arena gruesa", "0.5-1", "200-400"}, {"Arena media", "0.25-0.5", "100-200"}, {"Arena fina", "0.1-0.25", "50-100"}, {"Arena muy fina", "0.05-0.1", "10-50"}}),
})

-- ------------------------------------------------------------ 03
CAP("C03", "Interferencia e imágenes", {
  h("Superposición"),
  f([[\Delta h_{T} = \frac{1}{2 \pi T} \Sigma Q_{i} \ln \p{\frac{R_{i}}{r_{i}}}]], "Sólo pozos con ri < Ri. ¡Libre: linealizar!"),
  f([[\Delta h_{T} = \frac{Q}{2 \pi T} \ln \p{\frac{R^{n}}{r_{1} r_{2} \cdots r_{n}}}]], "n pozos con igual Q y R"),
  h("Recarga lineal (imagen inyecta −Q)"),
  f([[\Delta h = \frac{Q}{2 \pi T} \ln \frac{r_{i}}{r_{r}}]], "rr < R y ri < R"),
  f([[\Delta h = \frac{Q}{2 \pi T} \ln \frac{R}{r_{r}}]], "rr < R ≤ ri ;  Δh = 0 si ambos ≥ R"),
  h("Barrera impermeable (imagen extrae +Q)"),
  f([[\Delta h = \frac{Q}{2 \pi T} \ln \frac{R^{2}}{r_{i} r_{r}}]], "rr < R y ri < R"),
  f([[\Delta h = \frac{Q}{2 \pi T} \ln \frac{R}{r_{r}}]], "rr < R ≤ ri"),
  n("Esquina de recarga: 3 imágenes (−Q, −Q, +Q). Recarga + barrera: verificar 2b + a < R y 2a + b < R (imágenes de imágenes)."),
  h("Pozo en varias napas"),
  f([[Q = \frac{2 \pi}{\ln \p{\frac{R}{r}}} \Sigma \Delta h_{i} K_{i} m_{i}]]),
  f([[\Delta h_{T} = \Delta h_{1} \p{\frac{T_{1} + T_{2}}{T_{2}}}]], "Condición inicial: una napa alimenta a la otra"),
  f([[Q = Q_{0} + \frac{2 \pi K_{2} m_{2} \Delta h_{2}}{\ln \p{\frac{R}{r_{0}}}}]], "N.E. en el estrato impermeable de la napa 2"),
})

-- ------------------------------------------------------------ 04
CAP("C04", "Redes de flujo y analogías", {
  h("Funciones potencial y de flujo"),
  f([[\phi = K h \qquad \nabla^{2} \phi = 0 \qquad \nabla^{2} \psi = 0]]),
  f([[v_{x} = \frac{\partial \phi}{\partial x} = -\frac{\partial \psi}{\partial z} \qquad v_{z} = \frac{\partial \phi}{\partial z} = \frac{\partial \psi}{\partial x}]], "Cauchy–Riemann"),
  f([[m_{\psi} \cdot m_{\phi} = -1]], "Familias ortogonales"),
  h("Caudal"),
  f([[\Delta q = K \frac{h}{N_{d}} \frac{a}{l} \qquad q = K h \frac{N_{t}}{N_{d}} \frac{a}{l}]], "Nt: canales; Nd: caídas; a/l = 1 cuadrados"),
  h("Condiciones de borde"),
  b("Barrera impermeable y eje de simetría: líneas de flujo ψ."),
  b("Superficie de agua en reposo: equipotencial φ."),
  b("Superficie libre en movimiento: línea de flujo con p/γ = 0 (Δφ = KΔz)."),
  h("Medios heterogéneo y anisotrópico"),
  f([[\frac{K_{1}}{K_{2}} = \frac{\tan \alpha}{\tan \beta}]], "Refracción"),
  f([[x' = a x , \quad a = \sqrt{\frac{K_{z}}{K_{x}}} , \quad K_{eq} = \sqrt{K_{x} K_{z}}]], "Transformación del dominio"),
  h("Analogías"),
  f([[\bar{v} = \frac{\gamma b^{2}}{12 \mu} \frac{dh}{dx}]], "Hele–Shaw (placas paralelas)"),
  f([[i = \frac{1}{R} V \Leftrightarrow v = K \frac{\Delta h}{L}]], "Eléctrica (Ohm)"),
})

-- ------------------------------------------------------------ 05
CAP("C05", "Costero y régimen impermanente", {
  h("Intrusión salina (Ghyben–Herzberg)"),
  f([[h_{s} = h_{d} \p{\frac{\gamma_{d}}{\gamma_{s} - \gamma_{d}}} \approx 40 h_{d}]]),
  f([[h_{d}^{2} = \frac{N (R^{2} - r^{2})}{2 K (1 + \delta)} , \quad \delta = \frac{\gamma_{d}}{\gamma_{s} - \gamma_{d}}]], "Isla circular con recarga N"),
  h("Theis (1935) – confinado"),
  f([[\frac{\partial^{2} h}{\partial r^{2}} + \frac{1}{r}\frac{\partial h}{\partial r} = \frac{S}{T}\frac{\partial h}{\partial t}]]),
  f([[\Delta h = \frac{Q}{4 \pi T} W(u) , \qquad u = \frac{r^{2} S}{4 T t}]]),
  f([[W(u) = -0.5772 - \ln u + u - \frac{u^{2}}{2 \cdot 2!} + \frac{u^{3}}{3 \cdot 3!} - \cdots]]),
  tab({"u", "W(u)", "u", "W(u)"}, {{"1E-4", "8.63", "0.05", "2.47"}, {"5E-4", "7.02", "0.1", "1.82"}, {"1E-3", "6.33", "0.2", "1.22"},
    {"5E-3", "4.73", "0.5", "0.56"}, {"0.01", "4.04", "1", "0.219"}, {"0.02", "3.35", "2", "0.049"}}),
  h("Cooper–Jacob (u < 0.01)"),
  f([[\Delta h = \frac{Q}{4 \pi T} \ln \p{\frac{2.24 T t}{S r^{2}}}]], "Error: u = 0.2 → 20%; 0.14 → 10%; 0.09 → 5%"),
  f([[R(t) = \sqrt{\frac{2.24 T t}{S}} \qquad \Delta h = \frac{Q}{2 \pi T} \ln \frac{R(t)}{r}]]),
  f([[H^{2} - h^{2} = \frac{Q}{\pi K} \ln \p{\frac{R(t)}{r}}]], "Libre transiente"),
  h("Interferencia transiente"),
  f([[t_{i} = \frac{r_{i}^{2} S}{2.24 T}]], "Tiempo de influencia: el pozo afecta si t > ti"),
  f([[\Delta h_{A} = \Sigma \frac{Q_{i}}{4 \pi T} \ln \p{\frac{2.24 T t}{r_{i}^{2} S}}]]),
  n("Imágenes: si tr < t < ti sólo actúa el real. Si t > ti: recarga Δh = Q/(2πT) ln(ri/rr); barrera Δh = Q/(2πT) ln(R(t)²/(rr ri))."),
  h("Bombeo variable"),
  f([[\Delta h = \frac{1}{4 \pi T} \Sigma \pm Q_{i} \ln \p{\frac{2.24 T}{r^{2} S}(t - t_{i})}]], "t ≥ ti ; +Q enciende, −Q apaga"),
})

-- ------------------------------------------------------------ 06
CAP("C06", "Pruebas de bombeo", {
  h("Tipos de prueba"),
  b("Gasto variable (escalonada): define Qmax y la cota de la bomba."),
  b("Gasto constante: 24 h, 180 min estabilizado, con 80% de Qmax."),
  b("Recuperación: desde tf se detiene el bombeo."),
  h("Curva tipo de Theis"),
  f([[T = \frac{Q}{4 \pi \Delta h^{*}} W(u) \qquad S = \frac{4 T u t^{*}}{r^{2}}]], "Superponer log-log sin rotar; leer W, 1/u, Δh*, t*"),
  f([[W(u) = \frac{u^{4} + 8.573u^{3} + 18.059u^{2} + 8.635u + 0.268}{u e^{u}(u^{4} + 9.573u^{3} + 25.633u^{2} + 21.097u + 3.958)}]], "Aproximación para u ≥ 1"),
  h("Cooper–Jacob (semilog)"),
  f([[T = \frac{Q}{4 \pi a} = \frac{2.303 Q}{4 \pi \Delta s_{ciclo}} \qquad S = \frac{2.24 T t_{0}}{r^{2}}]], "a: pendiente vs ln t; t0: corte con Δh = 0"),
  f([[\Delta h' = \Delta h - \frac{\Delta h^{2}}{2H}]], "Acuífero libre: corregir descensos"),
  h("Otros métodos"),
  f([[\Delta h = \frac{Q}{4 \pi T} W(u, \alpha) , \quad \alpha = S \p{\frac{r_{0}}{r}}^{2}]], "Papadopulos–Cooper (pozos de gran diámetro)"),
  f([[\Delta h = \frac{Q}{4 \pi T} W\p{u, \frac{r}{B}} , \quad B = \sqrt{\frac{T m'}{K'}}]], "Hantush–Jacob (semiconfinado)"),
  h("Recuperación"),
  f([[s' = \frac{Q}{4 \pi T} \ln \p{\frac{t}{t - t_{f}}} \Rightarrow T = \frac{2.303 Q}{4 \pi \Delta s'}]]),
  h("Bordes"),
  b("Barrera impermeable: la pendiente se duplica."),
  b("Recarga: la curva se estabiliza (pendiente nula)."),
  f([[r_{2} = r_{1} \sqrt{\frac{t_{2}}{t_{1}}} \qquad d = \frac{r_{1} + r_{2}}{2}]], "Igual desviación que el descenso original"),
  h("Pérdidas en el pozo"),
  f([[s_{w} = B Q + C Q^{2} \qquad \frac{s_{w}}{Q} = B + C Q]]),
})

-- ------------------------------------------------------------ 07
CAP("C07", "Drenes – régimen permanente", {
  h("Dren interceptor"),
  f([[H^{2} - h_{0}^{2} = \frac{2 q}{K} x_{1} \qquad Q_{z} = (q - q') L]]),
  h("Drenes paralelos abiertos"),
  f([[H^{2} - h_{0}^{2} = \frac{f D^{2}}{4 K}]], "Donnan: drenes abarcan toda la napa"),
  f([[(H - h_{0})(H + h_{0} + 2d) = \frac{f D^{2}}{4 K}]], "Hooghoudt: d < 0.6 m (si no, usar d')"),
  h("Drenes cerrados"),
  f([[(H + d)^{2} - d^{2} = \frac{f D^{2}}{4 K} \p{1 + \alpha \frac{4 d}{D}}]], "Dagan (1964)"),
  f([[\alpha = -\frac{1}{\pi} \ln \b{2 \p{\cosh \p{\frac{\pi r_{0}}{d}} - 1}}]], "r0/d ≥ 0.3 ⇒ α → 0"),
  tab({"r0/d", "α", "r0/d", "α"}, {{"0.01", "2.16", "0.08", "0.86"}, {"0.02", "1.75", "0.10", "0.75"}, {"0.04", "1.31", "0.20", "0.29"}, {"0.06", "1.05", "0.30", "0.01"}}),
  f([[H = \frac{D f}{K \pi} \ln \p{\frac{D}{5.44 r_{0}}}]], "Superficiales, espesor infinito"),
  f([[H = \frac{D f}{K} F \p{\frac{2 r_{0}}{D}, \frac{d}{D}}]], "Kirkham (1958)"),
  tab({"d/D", "0.0025", "0.005", "0.01", "0.02", "0.04"}, {{"0.01", "12.79", "12.57", "12.33", "12.03", "11.52"}, {"0.02", "6.761", "6.541", "6.318", "6.077", "5.771"},
    {"0.04", "3.864", "3.643", "3.421", "3.195", "2.954"}, {"0.08", "2.522", "2.301", "2.080", "1.858", "1.633"}, {"0.16", "1.961", "1.741", "1.520", "1.299", "1.077"},
    {"0.32", "1.787", "1.566", "1.345", "1.125", "0.904"}, {"≥0.64", "1.764", "1.543", "1.323", "1.102", "0.811"}}),
  n("Columnas de la tabla de Kirkham: 2r0/D."),
  h("Infiltración típica"),
  tab({"Suelo", "f [mm/h]"}, {{"Arena", ">30"}, {"Arena limosa", "20-30"}, {"Limo", "10-20"}, {"Arcilla limosa", "5-10"}, {"Arcilla", "1-5"}}),
})

-- ------------------------------------------------------------ 08
CAP("C08", "Drenes – régimen impermanente", {
  h("Ecuación de continuidad"),
  f([[h \frac{\partial^{2} h}{\partial x^{2}} + \p{\frac{\partial h}{\partial x}}^{2} = \frac{S}{K} \frac{\partial h}{\partial t}]]),
  n("Moody (1964): gráficos y/y0 y qD/(Kπy0) vs α = K H0 t/(S D²), con m = y0/H0 (d ≠ 0)."),
  h("Glover–Dumm (1954)"),
  f([[y = h - d \qquad y_{0} = H_{0} - d \qquad \alpha = \frac{\pi^{2} K d}{S D^{2}}]]),
  f([[y = 1.16 y_{0} e^{-\alpha t}]], "x = D/2 y αt ≥ 0.2"),
  f([[D = \pi \sqrt{\frac{K d t}{S \ln \p{\frac{1.16 y_{0}}{y}}}}]]),
  h("Corrección de Hooghoudt (χ = π r0)"),
  f([[\frac{d'}{d} = \frac{1}{1 + \frac{8}{\pi} \frac{d}{D} \ln \p{\frac{d}{\chi}}}]], "d/D < 0.25"),
  f([[\frac{d'}{d} = \frac{\pi}{2 \p{\ln \p{\frac{D}{\chi}} + 0.18}}]], "d/D ≥ 0.25"),
  b("Iterar: D con d → d' con D → D con d' → hasta converger."),
  h("Equilibrio dinámico"),
  f([[y_{0,i} = y_{f,i-1} + \frac{R_{i}}{S} \qquad y_{f,i} = 1.16 y_{0,i} e^{-\alpha t_{i}}]]),
  f([[y_{f} \le y_{0} \qquad I_{s} = \int (y > y_{a}) dt \le 200 mm \cdot dia]]),
})

-- ------------------------------------------------------------ 09
CAP("C09", "Drenaje longitudinal", {
  h("Cuneta y contrafoso"),
  b("Ancho w ≥ 0.5 m; i1 ≥ 8% (w > 0.5 m), máx. 30% (w = 0.5 m)."),
  b("Pendiente longitudinal mínima: 0.12% revestida; 0.25% sin revestir."),
  b("Bombeo de la calzada i2 ≈ 2–4%."),
  h("Caudal (A < 25 km², td > tc)"),
  f([[Q_{max} = \frac{C \bar{i}(t_{c}) A}{3.6}]], "Q [m³/s]; i [mm/h]; A [km²]; verificar tc ≥ 10 min"),
  tab({"Autor", "tc [min]"}, {{"Normas Esp.", "18 L^0.76/S^0.19"}, {"California", "57 (L³/H)^0.385"}, {"Giandotti", "60(4√A+1.5L)/(0.8√Hm)"},
    {"SCS", "3.42 L^0.8 (1000/CN−9)^0.7/S^0.5"}}),
  n("L [km], S [%], H y Hm [m], A [km²]."),
  h("Precipitación de diseño"),
  f([[i_{t} = i_{24} \sqrt{\frac{24}{t}}]], "Grunsky [mm/h]"),
  f([[P_{t}^{T} = K \cdot CD_{t} \cdot CF_{T} \cdot P_{D}^{10} \qquad K = 1.1]]),
  f([[P_{t}^{T} = (0.54 t^{0.25} - 0.50)(0.21 \ln T + 0.52) P_{1}^{10}]], "Bell (t < 1 h, t en min)"),
  h("Coeficiente de escorrentía"),
  tab({"Terreno", "C"}, {{"Adoquín", "0.50-0.70"}, {"Asfalto", "0.70-0.95"}, {"Concreto", "0.80-0.95"}, {"Arenoso con vegetación", "0.15-0.20"},
    {"Arcilloso con pasto", "0.25-0.65"}, {"Cultivo", "0.20-0.40"}}),
  tab({"Factor", "Extremo", "Alto", "Normal", "Bajo"}, {{"Relieve", ".28-.35", ".20-.28", ".14-.20", ".08-.14"}, {"Infiltración", ".12-.16", ".08-.12", ".06-.08", ".04-.06"},
    {"Cobertura", ".12-.16", ".08-.12", ".06-.08", ".04-.06"}, {"Almacenam.", ".10-.12", ".08-.10", ".06-.08", ".04-.06"}}),
  n("Tabla para T = 10 años (sumar factores). T=25: ×1.10; T=50: ×1.20; T=100: ×1.25."),
  h("Altura de agua y velocidades"),
  f([[\frac{Q n}{\sqrt{S}} = \frac{\Omega^{5/3}}{\Psi^{2/3}}]], "Contrafoso de tierra n = 0.023–0.025"),
  tab({"Vmax [m/s]", "Suelo"}, {{"0.6", "Limo"}, {"0.9", "Arena"}, {"1.2", "Arcilla"}, {"3.0", "Asfalto"}, {"4.5", "Hormigón"}}),
  f([[v_{min} = 0.4 \sim 0.5 m/s \qquad R = 0.15 \sim 0.2 h]], "Smín: tierra 0.25%, asfalto 0.15%; R: revancha"),
  b("Contrafoso trapecial; verificar θ < φ (ángulo de fricción)."),
  h("Periodo de retorno"),
  f([[R = 1 - \b{1 - \frac{1}{T}}^{n}]]),
  tab({"Obra", "T dis.", "T ver.", "n", "R dis."}, {{"Carreteras", "10", "25", "10", "65%"}, {"Caminos", "5", "10", "5", "67%"}}),
  b("Bajadas: Ø ≥ 200 mm si H/V ≥ 4; gradería si H/V ≤ 4:1; v = 5 m/s."),
})

-- ------------------------------------------------------------ 10
CAP("C10", "Alcantarillas", {
  h("Generalidades"),
  b("Luz ≤ 6 m (MC 3.703.101); mayor = puente. Libre entre tubos D/2."),
  b("Seguir línea de flujo y pendiente del cauce; muros guía."),
  b("Horacio Mery: operar cercano al crítico, Fr 0.7–0.9."),
  h("Criterio 1: control de entrada (torrente)"),
  f([[H_{c} = \frac{3}{2} h_{c} \qquad h_{c} = \sqrt[3]{\frac{Q^{2}}{g b^{2}}}]], "Rectangular; se impone D = H = Hc"),
  f([[D = \frac{3}{2} \frac{1}{g^{1/3}} \p{\frac{Q}{b}}^{2/3}]]),
  f([[S_{c} = \frac{2}{3} g H n^{2} \p{\frac{b + \frac{4}{3}H}{\frac{2}{3} H b}}^{4/3}]], "SD ≥ Sc ⇒ torrente; si no, SD = Sc"),
  f([[Q = 1.425 D^{5/2} \qquad S_{c} = \frac{31.14 n^{2}}{D^{1/3}}]], "Circular (hc = 0.7 D)"),
  b("Verificar v < 5 m/s y diseñar con D > H."),
  h("Criterio 2: verificación (T2)"),
  f([[S_{n} = \frac{10.3 Q_{2D}^{2} n^{2}}{D^{16/3}} \qquad \frac{Q_{2D} n}{\sqrt{S_{n}}} = \Omega R_{H}^{2/3}]], "Circular | Rectangular (hn = D)"),
  f([[H' = c_{c} D + \frac{1}{2g} \p{\frac{Q_{2D}}{b c_{c} D}}^{2}]], "Caso 1: SD > Sn (compuerta), cc ≈ 0.611"),
  f([[H' = D + \frac{1}{2g}(k_{e} + 1) \frac{Q_{2D}^{2}}{(D b)^{2}}]], "Caso 2: SD = Sn"),
  f([[H' = D + \frac{v_{2}^{2}}{2g} + \Lambda_{e} + J L - S_{D} L]], "Caso 3: SD < Sn"),
  f([[H' = D + \frac{v_{2}^{2}}{2g} + \Lambda_{e} + \Lambda_{s} + J L - S_{D} L]], "Control de salida"),
  f([[\Lambda_{e} = k_{e} \frac{v_{2}^{2}}{2g} \quad \Lambda_{s} = k_{s} \frac{(v_{2} - v_{3})^{2}}{2g} \quad J = \frac{v_{2}^{2} n^{2}}{R_{H}^{4/3}}]], "ks = 0.22–0.44 (0.4)"),
  tab({"Entrada", "ke"}, {{"Tubo saliente", "0.9"}, {"A ras de muro", "0.5"}, {"Abocinada", "0.2"}}),
  h("Periodos de retorno (MC V3)"),
  tab({"Obra", "Ruta", "Dis.", "Ver.", "n"}, {{"Puentes", "Carretera", "200", "300", "50"}, {"", "Camino", "100", "150", "50"},
    {"Alc. S>1.75 m²", "Carretera", "100", "150", "50"}, {"", "Camino", "50", "100", "30"}, {"Alc. S<1.75 m²", "Carretera", "50", "100", "50"}, {"", "Camino", "25", "50", "30"}}),
  h("Carga de diseño He"),
  tab({"Cauce", "Tubos", "Cajones", "Losas"}, {{"Canales", "D", "H", "H−0.10"}, {"Diseño natural", "D+0.3", "H+0.3", "H−0.10"}, {"Verif. natural", "D+0.6", "H+0.6", "H"}}),
  n("He máximo: cota exterior del SAP − 0.3 m."),
  h("Secciones"),
  tab({"Sección", "A", "P", "B"}, {{"Rect.", "b y", "b+2y", "b"}, {"Trapecio", "(b+ky)y", "b+2y√(1+k²)", "b+2ky"}, {"Triáng.", "k y²", "2y√(1+k²)", "2ky"},
    {"Circular", "(θ−senθ)D²/8", "θD/2", "D sen(θ/2)"}}),
  f([[\theta = 2 \text{arccos} \p{1 - \frac{2y}{D}}]]),
})

-- ------------------------------------------------------------ 11
CAP("C11", "Puentes", {
  h("Recomendaciones"),
  b("No generar resaltos; no peraltar aguas arriba; evitar socavación."),
  b("Opción 1: terraplén y estribos (fusible). Opción 2: cepas."),
  h("Opción 1: largo mínimo L (momenta)"),
  f([[M_{1} = \frac{Q^{2}}{g (b h_{1})} + \frac{h_{1}}{2} (b h_{1})]]),
  f([[M_{2} = \frac{Q^{2}}{g (L h_{2})} + \frac{h_{2}}{2} (b h_{2})]]),
  f([[h_{c2,M} = \sqrt[3]{\frac{Q^{2}}{g b L}}]], "Condición: M1 = M2c ⇒ L ≥ Lmin"),
  h("Energía"),
  f([[h_{2} + \frac{v_{2}^{2}}{2g} = h_{n1} + \frac{v_{1}^{2}}{2g} + \Lambda_{s}]], "Entre (1) y (2)"),
  f([[\Lambda_{s} = \frac{(v_{2} - v_{1})^{2}}{2g} - \frac{(h_{n1} - h_{2})^{2}}{2 h_{n1}}]], "Borda"),
  f([[h_{3} + \frac{v_{3}^{2}}{2g} = h_{2} + \frac{v_{2}^{2}}{2g} + \Lambda_{e} , \quad \Lambda_{e} = k_{e} \frac{v_{2}^{2}}{2g}]], "ke = 0.1–0.3; verificar h3 < hmax y v2 < vmax"),
  f([[\frac{1}{X_{2}} - \frac{1}{n X_{3}} = \frac{1}{2}(X_{3}^{2} - X_{2}^{2})]], "Momentum 3–2: X = h/hc2, n = b3/b2"),
  h("Opción 2: cepas (Yarnell)"),
  f([[\frac{h_{3} - h_{1}}{h_{1}} = K Fr_{1}^{2} (K + 5 Fr_{1}^{2} - 0.6)(\sigma + 15 \sigma^{4})]], "σ = 1 − be/b ; be = b − nD"),
  tab({"Forma de la cepa", "K"}, {{"Nariz y cola semicircular", "0.90"}, {"Doble cilindro con diafragma", "0.95"}, {"Doble cilindro sin diafragma", "1.05"},
    {"Triangular 90°", "1.05"}, {"Cuadrada", "1.25"}, {"Trestle bent 10 pilotes", "2.50"}}),
})

-- ------------------------------------------------------------ 12
CAP("C12", "Drenaje urbano", {
  h("Cunetas"),
  f([[Q = \frac{\sqrt{S}}{n} \frac{b^{2} i}{2} \p{\frac{b i}{2(i + 1)}}^{2/3}]], "Simple: y = b i ≤ 15 cm, b ≤ 1–2 m, i = 2–4%"),
  f([[Q = 0.315 \frac{\sqrt{S}}{n} b^{8/3} \b{i_{2} + (i_{1} - i_{2})\p{\frac{w}{b}}^{2}}^{5/3}]], "Compuesta: w ≈ 0.6 m; i1 = 2–10%"),
  h("Sumidero horizontal de fondo"),
  f([[Q_{m} = 1.66 (L_{e} + 2 w_{e}) h^{1.5}]], "Vertedero: h < 1.6 Ae/(Le + 2we)"),
  f([[Q_{m} = 2.66 A_{e} h^{0.5}]], "Orificio: h ≥ 1.6 Ae/(Le + 2we)"),
  f([[w_{e} = w - e n_{L} \quad L_{e} = L - e n_{T} \quad A_{e} = L_{e} w_{e}]], "w = 0.4–0.7 m; L = 1–2 m"),
  f([[\eta_{H} = R_{f} \eta_{0} + R_{s}(1 - \eta_{0}) \qquad \eta_{0} = 1 - \p{1 - \frac{w}{b_{s}}}^{2.67}]]),
  f([[R_{s} = \frac{1}{1 + \frac{0.0828 v^{1.8}}{i L^{2.3}}} \qquad R_{f} = 1 - 0.295(v - v_{0})]]),
  h("Sumidero lateral (S < 3%)"),
  f([[Q_{m} = 1.27 L h^{1.5} (h < a) \qquad Q_{m} = 2.66 L a h^{0.5} (h \ge a)]]),
  f([[\eta_{L} = 1 - \p{1 - \frac{L}{L_{T}}}^{1.8} \qquad L_{T} = 0.81 Q^{0.42} S^{0.3} (n i)^{-0.6}]], "ηL = 1 si h > a; mixto: (ηH + ηL)Q"),
  h("Factor de seguridad (ηd = F η)"),
  tab({"Caudal", "Mantención", "F"}, {{"< 30 L/s", "buena", "1.0"}, {"", "mala", "0.8"}, {"> 30 L/s", "buena", "0.7"}, {"", "mala", "0.6"}}),
  h("Separación entre sumideros"),
  f([[L = \frac{3600 (F \eta) Q_{max}}{C i b_{c}}]], "i (Tr 2 años, 30 min); bc = 0.5e + wc (doble bombeo) o e + wc"),
  b("Tormentas menores (Tr 2–10): ancho recomendado, tc ≥ 30 min."),
  b("Tormentas mayores (Tr 50–100): bajo solera y h < 15 cm."),
  h("Colectores"),
  b("Ø 300 mm a 2 m; h ≤ 0.8D; D > 0.8 m primario (DOH), ≤ 0.8 m SERVIU."),
  f([[V_{c} = 0.397 \frac{D^{2/3} \sqrt{S}}{n} \ge 0.6 m/s]], "Autolavado"),
  tab({"Situación", "h", "θ", "A", "Rh"}, {{"Llena", "D", "360°", "0.785D²", "0.250D"}, {"Q máx", "0.95D", "308°", "0.771D²", "0.287D"}, {"Diseño", "0.80D", "254°", "0.674D²", "0.304D"}}),
  tab({"Tubería", "vmax [m/s]"}, {{"Concreto ≤ 45 cm", "3.0"}, {"Concreto armado ≥ 61 cm", "3.5"}, {"Fibrocemento / PVC / HDPE", "5.0"},
    {"Acero corrugado", "4.5"}, {"Acero con shotcrete", "3.0"}, {"PRFV", "3.5"}}),
  b("Profundidad: aguas lluvias 1.8 m; agua potable 1–1.5 m. Cámaras cada 50–130 m y trampas de arena."),
  h("Caudales en red (racional)"),
  f([[Q_{D2} = \text{max}(Q_{D1}, Q_{2}, Q_{2I}) \qquad Q_{2I} = \frac{\bar{C}_{1,2} \bar{i}(t_{c2I})(A_{1} + A_{2})}{3.6}]]),
  f([[t_{c2I} = \text{max}(t_{c1} + t_{t1}, t_{c2}) \qquad t_{t1} = \frac{L_{1}}{v_{1}}]]),
  h("Hidrograma SCS"),
  f([[t_{p} = \frac{t_{LL}}{2} + 0.6 t_{c} \quad t_{r} = 1.67 t_{p} \quad t_{B} = 2.67 t_{p}]]),
  f([[Q_{p} = \frac{2 P_{ef} A}{2.67 \p{\frac{t_{LL}}{2} + 0.6 t_{c}}}]]),
})

-- ------------------------------------------------------------ constantes
CAP("REF", "Constantes y unidades", {
  h("Constantes"),
  f([[g = 9.81 m/s^{2} \qquad \gamma_{w} = 9810 N/m^{3} \qquad \mu = 10^{-3} Pa \cdot s]]),
  h("Conversiones"),
  tab({"De", "A", "Factor"}, {{"cm/s", "m/s", "×0.01"}, {"m/día", "m/s", "÷86400"}, {"mm/día", "m/s", "÷8.64E7"}, {"L/s", "m³/s", "÷1000"},
    {"km²", "m²", "×1E6"}, {"ha", "m²", "×1E4"}, {"darcy", "m²", "9.87E−13"}, {"log10", "ln", "ln = 2.303 log"}}),
  h("Racional con otras unidades"),
  f([[Q[m^{3}/s] = \frac{C i[mm/h] A[km^{2}]}{3.6} = \frac{C i[mm/h] A[ha]}{360}]]),
})
